// =============================================================================
// app/track/[id]/page.tsx
//
// Route: /track/[bookingId]?token=[trackingToken]
//
// The public appointment tracking page. Customers reach this page by clicking
// the link in their confirmation or reminder email.
//
// HOW SECURITY WORKS HERE:
//   The URL contains the booking ID (UUID) AND a token query parameter.
//   The page fetches the booking from the database by token, not by ID.
//   That means even if someone knows a booking's UUID, they cannot view it
//   without also knowing the 64-character random token.
//   The token is generated by lib/security.ts at booking creation time and
//   is never shown anywhere except in that customer's email.
//
// DATA FLOW:
//   1. Server renders this page with the booking data pre-fetched
//   2. The TrackingWidget component receives that data as initialBooking
//   3. TrackingWidget polls GET /api/bookings/[id]?token=... every 30 seconds
//      for live updates, using the same token validation on the server
//
// THIS FILE IMPORTS:
//   next                           -- Metadata
//   next/navigation                -- notFound
//   lib/db.ts                      -- getBookingByToken
//   components/TrackingWidget.tsx  -- the live-updating UI
// =============================================================================

import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { getBookingByToken } from "@/lib/db";
import TrackingWidget from "@/components/TrackingWidget";

// Next.js passes URL params and query strings into the page as props.
// In Next.js 15+, params and searchParams are Promises and must be awaited.
interface TrackPageProps {
  params:      Promise<{ id: string }>;
  searchParams: Promise<{ token?: string }>;
}

export const metadata: Metadata = {
  title: "Track Your Appointment",
};

export default async function TrackPage({ params, searchParams }: TrackPageProps) {
  const { id } = await params;
  const { token } = await searchParams;

  // If the URL has no token at all, immediately show a 404 page.
  // notFound() triggers Next.js's built-in 404 handler.
  if (!token) {
    notFound();
  }

  // Fetch the booking by token (not by the ID in the URL).
  // The token is the actual security gate.
  const booking = await getBookingByToken(token);

  // If no booking matches this token, or if the booking ID in the URL
  // does not match the token's booking (tampered URL), show 404.
  if (!booking || booking.id !== id) {
    notFound();
  }

  return (
    <main className="min-h-screen bg-brand-cream py-16 px-4">
      <div className="max-w-lg mx-auto mb-8 text-center">
        <h1 className="font-display text-3xl font-bold text-brand-dark mb-2">
          Your Appointment
        </h1>
        <p className="text-gray-500 text-sm">
          {booking.customer_name} - {booking.service_type.replace("-", " ")}
        </p>
      </div>
      {/* Pass the server-fetched booking as the initial prop.
          TrackingWidget will poll for updates automatically after mount. */}
      <TrackingWidget initialBooking={booking} token={token} />
    </main>
  );
}
